### PR TITLE
some change about speed and altitude

### PR DESCRIPTION
**Pull request by macfly1202**
- change osd_alt to osd_rel_alt
- change groundspeed to airspeed except for distance calculation

### CODE REVIEW

**Comment by ghost** [comment]
Looks great, thanks! I will add an option at config tool for choosing.

**Comment by macfly1202** [comment]
Like on vector, and for people who live where there are mountains : 

> best is to have the relative on ladder and at the bottom of the screen, the real altitude like here on one of my video : 
> https://youtu.be/_JEJAQeGxJg   > the G with arrow below

**Comment by ghost** [comment]
We can make the scale bar to be configurable to show real altitude or relative altitude. Then we have two items(text) to show altitude separately. The same to speed. How about that?

**Comment by macfly1202** [comment]
Hi, for me relative alt is good on scale bar. But if not to difficult, why not adding it.
I suppose a variometer will be better for most people like on Vector OSD or Luis > 'Alceosd'   

Generally all osd ask which speed to display in ladder : groundspeed or airspeed (if pitot often).
Then you choose if you want to display in more, below, on bottom of each ladder, airspeed again or grounspeed or the two value.

Hope I m crystal clear !

**Comment by macfly1202** [comment]
I found anothe rproblem with ALT on screen 2. I will correct it and pull request soon. 
Lot of people asking where to find the osd tool WITH last firwmware.  Could you explain how to find it ? (it s not for me but for other guy who ask me)

**Pull request merged**
